spring.cloud.vault:
  host: localhost
  port: 8200
  scheme: https
  uri: https://vault:8200
  connection-timeout: 5000
  read-timeout: 15000
  token: hvs.9Vt8YckP5gH53aLtF8XxabYl
spring.config.import: vault://spring-boot-example/apps